
export const UNKNOWN_ERROR_CODE = 'UNKNOWN_ERROR';

export const ERROR_CODES = {
    UNKNOWN_ERROR : 'INTERNAL_SERVER_ERROR',

    ACTION_NOT_PERMITTED : 'PERMISSION_DENIED',
    TOKEN_EXPIRED        : 'PERMISSION_DENIED',
    WRONG_TOKEN          : 'PERMISSION_DENIED',

    PERMISSION_MISSMATCH : 'OPERATION_CONFLICT',
    VALIDATION_FAILED    : 'FORMAT_ERROR',
    VERSION_NOT_FOUND    : 'NOT_FOUND'
};
